# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\" \n\x0bTaskRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"?\n\x0cTaskResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\x32I\n\rWorkerService\x12\x38\n\x0bRequestTask\x12\x13.worker.TaskRequest\x1a\x14.worker.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKREQUEST']._serialized_start=24
  _globals['_TASKREQUEST']._serialized_end=56
  _globals['_TASKRESPONSE']._serialized_start=58
  _globals['_TASKRESPONSE']._serialized_end=121
  _globals['_WORKERSERVICE']._serialized_start=123
  _globals['_WORKERSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
